# Docker
alias d='docker'
alias dr='docker run --rm -it'
alias de='docker exec -it'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dl='docker logs'
alias dlf='docker logs -f'
alias ddf='docker system df'
dsh() { docker exec -it ${1} sh; }

# Docker-Compose
alias dc='docker-compose'
alias dcb='docker-compose build'
alias dcbp='docker-compose build --pull'
alias dcb!='docker-compose build --pull --no-cache'
alias dcd!='docker-compose down -v --remove-orphans'
alias dce='docker-compose exec'
alias dcl='docker-compose logs'
alias dclf='docker-compose logs -f'
alias dcp='docker-compose pull'
alias dcps='docker-compose ps'
alias dcr='docker-compose run --rm'
alias dcu='docker-compose up'
alias dcud='docker-compose up -d'
